name: expense_tracker
description: "Your pocket, Your control"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/add.png
    - assets/images/expenzy.png
  # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/font/Inter-Regular.ttf
  #       - asset: assets/font/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/font/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/font/Inter-Bold.ttf
  #         weight: 700
